%YAML:1.0
---
# Kinect相机配置示例
# 相机类型: kinect 或 hik
camera_type: kinect

# 相机内参矩阵 (根据用户提供数据)
camera_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [611.8028564453125, 0, 637.162353515625,
          0, 611.7578125, 369.3819580078125,
          0, 0, 1]

# 畸变系数 (根据用户提供数据)
dist_coeffs: !!opencv-matrix
   rows: 5
   cols: 1
   dt: d
   data: [0, 0, 0, 0, 0]

# ArUco 字典与标签大小
aruco_dict_id: 0  
aruco_marker_length: 0.60

# ArUco 中心点到地面高度 (米)
H_marker: 0.325

# 数据记录相关参数
record_enabled: 1  # 1 表示启用记录, 0 表示禁用
launch_rpm: 3939   # 发射时的转速 (RPM)
record_dir: "../records"  # 保存CSV的文件夹
max_ball_gap: 120    # 若两帧中心距超过该像素值，则视为误检并断开轨迹

# ROI 检测区域 (0~0.5): 左右/上下可单独设置
roi_left_margin_ratio: 0.05   # 左侧去除5%
roi_right_margin_ratio: 0.05  # 右侧去除5%
roi_top_margin_ratio: 0.0   # 上方不去除
roi_bottom_margin_ratio: 0.0 # 底部不去除

# (可选) 若仍使用旧版单边比例，可保留 roi_side_margin_ratio 键
roi_side_margin_ratio: 0.0

origin_offset: !!opencv-matrix  #aruco到发射机构的偏移
  rows: 1
  cols: 3
  dt: d
  data: [ 0.775, 5.0, -5.37 ]

# HSV 阈值
hsv_low: !!opencv-matrix
  rows: 1
  cols: 3
  dt: i
  data: [ 0, 0, 0 ]
hsv_high: !!opencv-matrix
  rows: 1
  cols: 3
  dt: i
  data: [ 255, 255, 255 ]

# 运动平面
motion_plane:
  point: !!opencv-matrix
    rows: 1
    cols: 3
    dt: d
    data: [ 0.0, 0.0, -5.47 ]
  normal: !!opencv-matrix
    rows: 1
    cols: 3
    dt: d
    data: [ 0.0, 0.0, 1.0 ]

# ROI 视频保存目录
roi_video_dir: "../roi_videos" 